version: "3"

services:
  app:
    build: docker/php
#    image: docker/cpanel-php
    restart: always
    volumes:
    - ./:/cpanel
    - /en:/en
    - /etc/hosts:/host-machine/hosts
#    - /disks:/disks
#    - ${DATA_PATH_HOST}/storage/source:/app/public/storage/source
    - ${HOME}/projects:/projects
    - ${HOME}/instances:/instances
    - ${HOME}/.ssh:/root/.ssh
    - ${HOME}/.composer:/root/.composer
    - ./docker/.bashrc:/root/.bashrc
  #    extra_hosts:
  #      - dev.entero.in:165.227.188.128
  nginx:
    build:
      context: docker/nginx
      args:
      - PHP_UPSTREAM_CONTAINER=app
      - PHP_UPSTREAM_PORT=9000
    restart: always
    volumes:
    #    - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    #    - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
    - ./docker/nginx/sites-available:/etc/nginx/sites-available
    - ./docker/nginx/ssl:/etc/nginx/ssl
    - ./:/cpanel
    - /en:/en
    - /etc/hosts:/host-machine/hosts
    - ${HOME}/projects:/projects
    - ${HOME}/instances:/instances
#    - /disks:/disks
#    - ${DATA_PATH_HOST}/storage/source:/app/public/storage/source
    - ${HOME}/apps:/root/apps
    - ${HOME}/disks:/root/disks
    - ./docker/.bashrc:/root/.bashrc
    - ./docker/data/certbot/conf:/etc/letsencrypt
    - ./docker/data/certbot/www:/var/www/certbot
    ports:
    - 80:80
    - 443:443
    depends_on:
    - app
  db:
    image: mysql:5.7
    restart: always
    volumes:
    - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    - /disks:/disks
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${CP_DB_ROOT_PASSWOD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${CP_DB_USERNAME}
      MYSQL_PASSWORD: ${CP_DB_ROOT_PASSWOD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: ${CP_DB_USERNAME}
      MYSQL_PASSWORD: ${CP_DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${CP_DB_ROOT_PASSWOD}
    ports:
    - 8080:80
    links:
    - db

